"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class CreateFHIRSurveyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FHIR_QUESTIONNAIRE_FIELD_NUMBER: builtins.int
    @property
    def fhir_questionnaire(self) -> google.protobuf.struct_pb2.Struct:
        """FHIR questionnaire on a gRPC Struct format"""
        pass
    def __init__(self,
        *,
        fhir_questionnaire: typing.Optional[google.protobuf.struct_pb2.Struct] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fhir_questionnaire",b"fhir_questionnaire"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fhir_questionnaire",b"fhir_questionnaire"]) -> None: ...
global___CreateFHIRSurveyRequest = CreateFHIRSurveyRequest

class SurveyFHIRAnswersResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SURVEY_ID_FIELD_NUMBER: builtins.int
    FHIR_QUESTIONNAIRE_RESPONSES_FIELD_NUMBER: builtins.int
    survey_id: typing.Text
    """The project identifier for this survey. Equal to the parent of the corresponding Agent.
    Format: `projects/<Project ID>/agent`.
    """

    @property
    def fhir_questionnaire_responses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
        """all requested answers"""
        pass
    def __init__(self,
        *,
        survey_id: typing.Text = ...,
        fhir_questionnaire_responses: typing.Optional[typing.Iterable[google.protobuf.struct_pb2.Struct]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fhir_questionnaire_responses",b"fhir_questionnaire_responses","survey_id",b"survey_id"]) -> None: ...
global___SurveyFHIRAnswersResponse = SurveyFHIRAnswersResponse
